# Generated by Django 5.2.5 on 2025-08-20 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='Bio',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='store',
            name='brand_logo',
            field=models.ImageField(default='', upload_to='brands/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='store',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='store',
            name='total_views',
            field=models.IntegerField(default=0),
        ),
    ]
