# Generated by Django 5.2.5 on 2025-08-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_store_bio_alter_store_brand_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='brand_logo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
