# Generated by Django 5.2.5 on 2025-09-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_item_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='currency',
            field=models.CharField(blank=True, default='NGN', max_length=5, null=True),
        ),
    ]
