# Generated by Django 5.2.4 on 2025-09-29 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='total_orders',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
