# Generated by Django 5.2.5 on 2025-08-24 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_store_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='social',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
