# Generated by Django 5.2.5 on 2025-11-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_item_name_alter_item_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeimage',
            name='background_color',
            field=models.CharField(default='#ffffff', help_text='Hex color (e.g. #F5F5F5)', max_length=20),
        ),
    ]
