# Generated by Django 5.2.5 on 2025-08-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='business_type',
            field=models.CharField(blank=True, choices=[('retail', 'Retail'), ('services', 'Services'), ('food', 'Food & Beverage'), ('fashion', 'Fashion'), ('tech', 'Technology'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
