# Generated by Django 5.2.5 on 2025-11-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_storeimage_background_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeimage',
            name='background_color',
        ),
        migrations.AddField(
            model_name='store',
            name='background_color',
            field=models.CharField(default='#ffffff', help_text='Hex color (e.g. #F5F5F5)', max_length=20),
        ),
    ]
