# Generated by Django 5.2.5 on 2025-11-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_store_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='depop_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='facebook_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='order_system',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('depop', 'Depop')], default='whatsapp', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='tiktok_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
