# Generated by Django 5.2.5 on 2025-09-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_item_created_at_item_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeimage',
            name='currency',
            field=models.CharField(choices=[('NGN', 'Naira (₦)'), ('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)')], default='NGN', max_length=3),
        ),
        migrations.AlterField(
            model_name='storeimage',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
