# Generated by Django 5.2.5 on 2025-11-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_item_depop_link_item_facebook_link_item_order_system_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='depop_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='facebook_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='order_system',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('depop', 'Depop')], default='whatsapp', max_length=20),
        ),
        migrations.AddField(
            model_name='store',
            name='tiktok_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
