# Generated by Django 5.2.5 on 2025-12-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_item_currency_alter_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeimage',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
