# Generated by Django 5.2.5 on 2026-01-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_storetemplate_store_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='storetemplate',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='template_previews/'),
        ),
    ]
