# Generated by Django 5.2.5 on 2026-01-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_storetemplate_preview_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='storetemplate',
            name='html_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
