# Generated by Django 5.2.5 on 2026-01-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_storetemplate_html_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='depop_link',
            new_name='instagram_link',
        ),
        migrations.RemoveField(
            model_name='store',
            name='Bio',
        ),
        migrations.RemoveField(
            model_name='store',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='store',
            name='social',
        ),
        migrations.RemoveField(
            model_name='storetemplate',
            name='html_content',
        ),
        migrations.AddField(
            model_name='store',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='brand_story',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='founder_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='mission',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='storetemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storetemplate',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='order_system',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('facebook', 'Facebook Messenger')], default='whatsapp', max_length=20),
        ),
        migrations.AlterField(
            model_name='store',
            name='total_views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='storetemplate',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='store',
            name='bio',
            field=models.TextField(default='', help_text='Short brand description'),
            preserve_default=False,
        ),
    ]
