# Generated by Django 5.2.5 on 2026-01-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_rename_depop_link_store_instagram_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='about',
            field=models.TextField(blank=True, default='No About Set', null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='brand_story',
            field=models.TextField(blank=True, default='No Story Set', null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='founder_name',
            field=models.CharField(blank=True, default='Unknown', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='mission',
            field=models.TextField(blank=True, default='No Mission Set', null=True),
        ),
    ]
