# Generated by Django 5.2.5 on 2026-01-05 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_store_about_alter_store_brand_story_and_more'),
    ]

    operations = [
    ]
