# Generated by Django 5.2.5 on 2026-05-22 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_add_new_store_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='background_color',
        ),
    ]
