# Generated by Django 5.2.5 on 2026-08-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_supplieraccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
    ]
